_wandb:
    value:
        cli_version: 0.21.0
        e:
            erjf7t00owinyxy1bac49p8pii8wblgr:
                codePath: scripts/nn.py
                codePathLocal: nn.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134860537856"
                        used: "1295048704"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 672a31223b17d786b9f390c77601a488332e56d3
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-b3e9e8c3-a543-5371-cf4e-ae24588677c8
                host: nid001025
                memory:
                    total: "269721079808"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/nn.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1757369305"
                    job_gid: "109311"
                    job_gpus: "2"
                    job_id: "42615879"
                    job_licenses: u1:1
                    job_name: jupyter
                    job_nodelist: nid001025
                    job_num_nodes: "1"
                    job_partition: shared_urgent_gpu_ss11
                    job_qos: gpu_shared_jupyter
                    job_start_time: "1757347705"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "42615879"
                    localid: "0"
                    mem_per_cpu: "1796"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001025
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001025
                    submit_dir: /global/u1/s/sferrett
                    submit_host: login05
                    task_pid: "1683026"
                    tasks_per_node: "1"
                    topology_addr: nid001025
                    topology_addr_pattern: node
                    tres_bind: gres/gpu:per_task:1
                    tres_per_task: cpu=32,gres/gpu=1
                startedAt: "2025-09-08T17:49:40.094967Z"
                writerId: erjf7t00owinyxy1bac49p8pii8wblgr
        m:
            - "1": Epoch
              "6":
                - 3
              "7":
                - 6
            - "1": Training loss
              "5": 1
              "6":
                - 1
                - 3
              "7":
                - 6
            - "1": Validation loss
              "5": 1
              "6":
                - 1
                - 3
              "7":
                - 6
            - "1": Learning rate
              "5": 1
              "6":
                - 1
                - 3
              "7":
                - 6
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 16
                - 62
                - 63
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
Early stopping patience:
    value: 3
Initial learning rate:
    value: 0.0001
Input variables:
    value: '"capeprofile", "subsatprofile"'
Learning rate scheduler:
    value: ReduceLROnPlateau (factor=0.5)
Loss function:
    value: Mean squared error
Mask below-surface values:
    value: false
Maximum training epochs:
    value: 30
Model parameter count:
    value: 52673
Network architecture:
    value: 256→128→64→32→1 (GELU + BatchNorm)
Optimizer:
    value: Adam
Training batch size:
    value: 64000
