_wandb:
    value:
        cli_version: 0.21.0
        e:
            p4zr6soobd9l347h14773ab230p6kjes:
                codePath: scripts/nn-standard.py
                codePathLocal: nn-standard.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134862802944"
                        used: "558120960"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 672a31223b17d786b9f390c77601a488332e56d3
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-4b4141df-e45b-05f6-717b-70bbb96b6793
                host: nid001000
                memory:
                    total: "269725609984"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/nn-standard.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1756337040"
                    job_gid: "109311"
                    job_gpus: "2"
                    job_id: "42082388"
                    job_licenses: u1:1
                    job_name: jupyter
                    job_nodelist: nid001000
                    job_num_nodes: "1"
                    job_partition: shared_urgent_gpu_ss11
                    job_qos: gpu_shared_jupyter
                    job_start_time: "1756315440"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "42082388"
                    localid: "0"
                    mem_per_cpu: "1796"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001000
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001000
                    submit_dir: /global/u1/s/sferrett
                    submit_host: login20
                    task_pid: "843370"
                    tasks_per_node: "1"
                    topology_addr: nid001000
                    topology_addr_pattern: node
                    tres_bind: gres/gpu:per_task:1
                    tres_per_task: cpu=32,gres/gpu=1
                startedAt: "2025-08-27T17:47:45.442006Z"
                writerId: p4zr6soobd9l347h14773ab230p6kjes
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 64000
input_variables:
    value:
        - cape
        - subsat
loss_function:
    value: L1Loss
n_params:
    value: 44993
name:
    value: exp_2
patience:
    value: 3
