_wandb:
    value:
        cli_version: 0.21.0
        e:
            qt24z65jtb4yyp54hqie6qxoqnbn67yb:
                codePath: scripts/nn_new_debug.py
                codePathLocal: nn_new_debug.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "134862782464"
                        used: "570839040"
                email: savannah.ferretti@uci.edu
                executable: /global/homes/s/sferrett/.conda/envs/monsoon-sr/bin/python
                git:
                    commit: 672a31223b17d786b9f390c77601a488332e56d3
                    remote: https://github.com/savannahferretti/monsoon-sr.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-3f3ddfb2-ab9d-2496-cbc1-1c04b8728537
                host: nid001029
                memory:
                    total: "269725564928"
                os: Linux-5.14.21-150500.55.97_13.0.78-cray_shasta_c-x86_64-with-glibc2.31
                program: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/nn_new_debug.py
                python: CPython 3.10.18
                root: /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts
                slurm:
                    cluster_name: perlmutter
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: m4334_g
                    job_cpus_per_node: "32"
                    job_end_time: "1756510362"
                    job_gid: "109311"
                    job_gpus: "2"
                    job_id: "42158592"
                    job_licenses: u1:1
                    job_name: jupyter
                    job_nodelist: nid001029
                    job_num_nodes: "1"
                    job_partition: shared_urgent_gpu_ss11
                    job_qos: gpu_shared_jupyter
                    job_start_time: "1756488762"
                    job_uid: "109311"
                    job_user: sferrett
                    jobid: "42158592"
                    localid: "0"
                    mem_per_cpu: "1796"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid001029
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: nid001029
                    submit_dir: /global/u1/s/sferrett
                    submit_host: login16
                    task_pid: "524750"
                    tasks_per_node: "1"
                    topology_addr: nid001029
                    topology_addr_pattern: node
                    tres_bind: gres/gpu:per_task:1
                    tres_per_task: cpu=32,gres/gpu=1
                startedAt: "2025-08-29T19:53:18.201871Z"
                writerId: qt24z65jtb4yyp54hqie6qxoqnbn67yb
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
Early Stopping Patience:
    value: 3
Initial Learning Rate:
    value: 0.001
Input Variables:
    value:
        - bl
Learning Rate Scheduler:
    value: ReduceLROnPlateau (factor=0.5)
Loss Function:
    value: Mean Squared Error
Maximum Training Epochs:
    value: 30
Model Parameter Count:
    value: 44737
Network Architecture:
    value: 256→128→64→32→1 (GELU + BatchNorm)
Optimizer:
    value: Adam
Training Batch Size:
    value: 64000
